"""create users table

Revision ID: 23f9ec0bbd8f
Revises: 872b04febb45
Create Date: 2026-07-17 17:47:27.748891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f9ec0bbd8f'
down_revision: Union[str, Sequence[str], None] = '872b04febb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enrollments_student_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_student_id_fkey'), 'enrollments', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
