"""create a transaction table

Revision ID: 3d1f1465ad40
Revises: 9d463c0191f6
Create Date: 2026-07-23 15:02:15.051012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1f1465ad40'
down_revision: Union[str, Sequence[str], None] = '9d463c0191f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'from_account',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'to_account',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'to_account',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'from_account',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
